package com.toel.service.Email;

public enum EmailTemplateType {
    DANGKYV3,OTP, PASSWORD_RESET, WELCOME, PASSWORD_SUSSECC, DANGKYV2, HUYDON, KHOATAIKHOAN, MOTAIKHOAN,DUYET,HUYDUYET,THEMCHIETKHAU,PHANHOIREPORT,DANGKYTAIKHOAN
}
