services:
  ebook_library_be:
    container_name: EbookLibraryBe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8080'

volumes:
  postgres-data:
  redis-data:

networks:
  my-network:
    driver: bridge
